[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_NETLIFY_IDENTITY = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  TOML_ENV = "Production"
